#cloud-config
users:
  - name: simon
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+bzs3vKiqnAGJG1zUTWemrdpzReUr7RJXZEdJukgAFKI1omNQ7GkPLNvvFwIj9/N7wMXWQOAf9c3IAACXJ1expfoTOzaPWcZ9xesNAWEyzFnSmQqa1y0+L4PL9M29HwGcHg6MDYITqv8oTJ3FC0jHdFdNHP761raUDt6d0fUaSWOs7uKJMltZ2D8HsfBb1NizOEJIw+0+1vT2TTUrYtCSAi6tJBWIXM6qCXeNa7IfSyW5vjmxEQgSRmmbQaZopUDIxJ2//juuick7ECriwP3/4GTq4liHk6EdIcum2ed+n9R/U+FCR5TUm+bAzoZUh8Nfh0ZL2SYbGayBYVv0db6j simon@simon-ubuntu

write_files:
  - path: /home/simon/config/service-prometheus-config.yml
    content: |
      storages:
        - name: main
          plugin: fs
          config:
            directory: /var/lib/yandex/unified_agent/main
            max_partition_size: 100mb
            max_segment_size: 10mb
      
      channels:
        - name: cloud_monitoring
          channel:
            pipe:
              - storage_ref:
                  name: main
            output:
              plugin: yc_metrics
              config:
                folder_id: b1g5ushnne9bb4in8beo
                iam:
                  cloud_meta: {}
      routes:
        - input:
            plugin: metrics_pull
            config:
              url: http://service-calculator-api:8085/api/actuator/prometheus
              format:
                prometheus: { }
              namespace: service-calculator-api
          channel:
            channel_ref:
              name: cloud_monitoring
      
        - input:
            plugin: agent_metrics
            config:
              namespace: ua
          channel:
            pipe:
              - filter:
                  plugin: filter_metrics
                  config:
                    match: "{scope=health}"
            channel_ref:
              name: cloud_monitoring

  - path: /home/simon/config/fluent-bit.conf
    content: |
      [SERVICE]
        Flush                   1
        Log_File                /var/log/fluentbit.log
        Log_Level               debug,trace
        Daemon                  off
        parsers_file            /fluent-bit/parsers/parsers.conf
        storage.path            /fluent-bit/log/storage/
      
      [INPUT]
        name                    tail
        path                    /logs/billing-api.log
        multiline.parser        multiline-regex
        storage.type            filesystem
      
      [FILTER]
        Name                    parser
        Key_Name                log
        Match                   *
        Parser                  billing_java_parser

      [OUTPUT]
        Name                    yc-logging
        Match                   *
        group_id                e23o31fhg9gpu0id85q8
        message_key             message
        level_key               level
        default_level           WARN
        authorization           instance-service-account

  - path: /home/simon/config/fluent-bit-parser.conf
    content: |
      [MULTILINE_PARSER]
        name multiline-regex
        type regex
        flush_timeout 1000
        rule    "start_state" "/(Dec \d+ \d+\:\d+\:\d+)(.*)/" "cont"
        rule    "cont" "/^\s+at.*/" "cont"

      [PARSER]
        Name        billing_java_parser
        Format      regex
        Regex       thread=(?<thread>[A-z-0-9]+) level=(?<level>\w+) requestId=(?<requestId>[A-z-0-9\/]+) stackTrace=(?<stackTrace>.*?\s)message=(?<message>.+)$
