create table accounting-point-key-room (id bigint generated by default as identity, accounting_point_id bigint not null, key-room_id bigint not null, primary key (id))
create table accounting_point_key_room_services (id bigint generated by default as identity, accounting_point_key_room_id bigint not null, service_id bigint not null, primary key (id))
create table accounting_point_meters (id bigint generated by default as identity, period timestamp, accounting_point_key_room_service_id bigint, meter_id bigint, primary key (id))
create table accounting_point_service_state (id bigint generated by default as identity, period timestamp, active boolean not null, accounting_point_key_room_service_id bigint, primary key (id))
create table accounting_points (id bigint generated by default as identity, description varchar(255) not null, primary key (id))
create table buildings (id bigint generated by default as identity, description varchar(255) not null, primary key (id))
create table customers (id bigint generated by default as identity, description varchar(255) not null, primary key (id))
create table differentiation_types (id bigint generated by default as identity, description varchar(255) not null, primary key (id))
create table direction_of_uses (id bigint generated by default as identity, description varchar(255) not null, primary key (id))
create table improvement_types (id bigint generated by default as identity, description varchar(255) not null, primary key (id))
create table key_rooms (id bigint generated by default as identity, building_id bigint not null, room_id bigint, primary key (id))
create table meter_types (id bigint generated by default as identity, description varchar(255) not null, primary key (id))
create table meters (id bigint generated by default as identity, description varchar(255) not null, meter_type_id bigint, primary key (id))
create table rate_groups (id bigint generated by default as identity, description varchar(255) not null, primary key (id))
create table room_squares (id bigint generated by default as identity, period timestamp, value integer not null, key_room_id bigint, square_type_id bigint, primary key (id))
create table rooms (id bigint generated by default as identity, description varchar(255) not null, building_id bigint not null, primary key (id))
create table services (id bigint generated by default as identity, description varchar(255) not null, primary key (id))
create table square_types (id bigint generated by default as identity, description varchar(255) not null, primary key (id))
alter table accounting-point-key-room add constraint FKljeli862wsufmrwjylh3p9ads foreign key (accounting_point_id) references accounting_points
alter table accounting-point-key-room add constraint FKsa96iuikhf8w1bxcvfjsnv1oo foreign key (key-room_id) references key_rooms
alter table accounting_point_key_room_services add constraint FKhsxadl30hnaym27rwjmfqutaj foreign key (accounting_point_key_room_id) references accounting-point-key-room
alter table accounting_point_key_room_services add constraint FKtotd3ob0h51dkxbewbij6f3sc foreign key (service_id) references services
alter table accounting_point_meters add constraint FKsk7wj2mxboof5dy3lagnf0kej foreign key (accounting_point_key_room_service_id) references accounting_point_key_room_services
alter table accounting_point_meters add constraint FKkxy6xy9lltbvcq7nchlijwe88 foreign key (meter_id) references meters
alter table accounting_point_service_state add constraint FK84n1toni0fb837rr2ix75i049 foreign key (accounting_point_key_room_service_id) references accounting_point_key_room_services
alter table key_rooms add constraint FKa6iw9mllq2ua3jd28r9h9qurg foreign key (building_id) references buildings
alter table key_rooms add constraint FKjxt8b2ixb06h2hlcvkyehtj70 foreign key (room_id) references rooms
alter table meters add constraint FK651xq90jh5n75y5l8cea3cl6m foreign key (meter_type_id) references meter_types
alter table room_squares add constraint FKaajnysb7edxn8e1of4nm6d7hc foreign key (key_room_id) references key_rooms
alter table room_squares add constraint FKbahu9ait9pnvht8j8swxlwc5m foreign key (square_type_id) references square_types
alter table rooms add constraint FKojgn0sxhkfxd7pmmojnem9r4q foreign key (building_id) references buildings
