server:
  port: 8085

  servlet:
    context-path: /api

spring:
  profiles:
    active: ${ENVIRONMENT:production}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  config: classpath:logging/${ENVIRONMENT:production}/logback.xml
  path: ${LOG_PATH:./logs/}
  file: billing-api

