server:
  port: 8085

  servlet:
    context-path: /api

spring:
  profiles:
    active: ${ENVIRONMENT:local}

logging:
  config: classpath:logging/${environment:local}/logback.xml
  path: ${LOG_PATH:./logs/}
  file: billing-api

