spring:
  server:
    port: ${server.port:8080}

  datasource:
    url: jdbc:postgresql://localhost:5432/AccountingPoint
    username: pguser
    password: pgpassword
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  liquibase:
    change-log: classpath:db/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmqUser
    password: rabbitmqPass




