version: "3.3"
services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=AccountingPoint
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.9.7-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmqUser
      RABBITMQ_DEFAULT_PASS: rabbitmqPass
    ports:
      - "5672:5672"
      - "15672:15672"


